name: Uptime Monitor

on:
  schedule:
    - cron: '0 * * * *' # Toutes les heures
  workflow_dispatch: # Permet le lancement manuel

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check website status
        run: |
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" https://lnk-studio.com/)
          if [ $STATUS -eq 200 ]; then
            echo "Website is UP (Status: $STATUS)"
          else
            echo "Website is DOWN (Status: $STATUS)"
            exit 1
          fi
